CREATE DATABASE IF NOT EXISTS snaptask_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE snaptask_db;

CREATE TABLE IF NOT EXISTS snap_user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS course (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  course_name VARCHAR(100) NOT NULL,
  teacher_name VARCHAR(100) DEFAULT '',
  color VARCHAR(32) DEFAULT '#2563EB',
  remark VARCHAR(500) DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_course_user_name (user_id, course_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ocr_record (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  image_path VARCHAR(500) DEFAULT '',
  ocr_text TEXT NOT NULL,
  recognize_status VARCHAR(30) NOT NULL DEFAULT '成功',
  ai_status VARCHAR(30) NOT NULL DEFAULT '未解析',
  generated_todo_id BIGINT DEFAULT NULL,
  generated_task_title VARCHAR(200) DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_parse_record (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  ocr_record_id BIGINT DEFAULT NULL,
  raw_ai_response TEXT,
  parsed_title VARCHAR(200) DEFAULT '',
  parsed_course VARCHAR(100) DEFAULT '',
  parsed_deadline DATETIME DEFAULT NULL,
  parsed_task_type VARCHAR(40) DEFAULT '其他',
  parsed_platform VARCHAR(60) DEFAULT '其他',
  parsed_priority VARCHAR(20) DEFAULT '中',
  parsed_description TEXT,
  parse_status VARCHAR(30) NOT NULL DEFAULT '成功',
  todo_generated TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS todo_task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  course_id BIGINT DEFAULT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  task_type VARCHAR(40) DEFAULT '其他',
  platform VARCHAR(60) DEFAULT '其他',
  deadline DATETIME DEFAULT NULL,
  priority VARCHAR(20) DEFAULT '中',
  status VARCHAR(20) DEFAULT '待完成',
  source_type VARCHAR(40) DEFAULT '手动创建',
  source_record_id BIGINT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
